In [1]:
import numpy as np

# Exercícios 01 sobre NumPy

## 01. Criação de Arrays

- a) Crie um array contendo os números de 10 a 30, pulando de 2 em 2;
- b) Gere uma matriz 3x4 preenchida apenas com o número 7;
- c) Crie um array de 100 valores aleatórios entre 0 e 1;
- d) Gere uma matriz identidade de tamanho 5x5.

In [3]:
# a) Crie um array contendo os números de 10 a 30, pulando de 2 em 2;
a = np.arange(10, 31, 2)

a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [8]:
# b) Gere uma matriz 3x4 preenchida apenas com o número 7;

# b = np.array([ [7, 7, 7, 7], [7, 7, 7, 7], [7, 7, 7, 7] ]) 

# OU PODE-SE FAZER DESSA OUTRA FORMA:

b = np.full((3,4), 7)

b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [7]:
# c) Crie um array de 100 valores aleatórios entre 0 e 1;

c = np.random.rand(100)

c

array([0.4288481 , 0.45800319, 0.92386864, 0.78768685, 0.32287734,
       0.11107191, 0.34783977, 0.43892953, 0.26492639, 0.96067577,
       0.67939565, 0.46734937, 0.07317025, 0.01208152, 0.52822492,
       0.50751535, 0.08706549, 0.99307317, 0.06884907, 0.95974778,
       0.04676943, 0.34090815, 0.72701891, 0.98037335, 0.27372225,
       0.51236295, 0.13066525, 0.8750051 , 0.67635218, 0.2845784 ,
       0.03235961, 0.91565767, 0.71251902, 0.20033999, 0.00493862,
       0.0695847 , 0.33722131, 0.5516678 , 0.41474988, 0.64602832,
       0.3730338 , 0.20047633, 0.91766735, 0.16947404, 0.68111702,
       0.54300394, 0.61956708, 0.60106479, 0.8511168 , 0.16812967,
       0.04460057, 0.86642426, 0.34207774, 0.82374266, 0.83689844,
       0.28772063, 0.53902089, 0.92212524, 0.47224997, 0.45152157,
       0.60227944, 0.02122509, 0.15311863, 0.25731541, 0.66120063,
       0.71165019, 0.65554538, 0.62020851, 0.47624525, 0.97032693,
       0.09813703, 0.21104265, 0.59441085, 0.46284333, 0.27804

In [11]:
# d) Gere uma matriz identidade de tamanho 5x5.
d = np.eye(5)

d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2. Indexação e Slicing

- a) Dado o array: `[5, 10, 15, 20, 25, 30, 35, 40]`, extraia apenas os valores maiores que 20;
- b) Pegue os 4 primeiros elementos desse array;
- c) Crie uma matriz 4x4 e selecione apenas a terceira coluna;
- d) Pegue as linhas 1 e 2 de uma matriz 4x4.

In [15]:
# a) Dado o array: [5, 10, 15, 20, 25, 30, 35, 40], extraia apenas os valores maiores que 20;
array1 = np.array([5, 10, 15, 20, 25, 30, 35, 40])

array1[array1 > 20]

array([25, 30, 35, 40])

In [16]:
# b) Pegue os 4 primeiros elementos desse array;

array1[:4]

array([ 5, 10, 15, 20])

In [25]:
# c) Crie uma matriz 4x4 e selecione apenas a terceira coluna;
array2 = np.array([ [1, 0, 3, 5], [1, 1, 6, 11], [2, 20, 3, 2], [3, 34, 7, 6] ])

array2

array([[ 1,  0,  3,  5],
       [ 1,  1,  6, 11],
       [ 2, 20,  3,  2],
       [ 3, 34,  7,  6]])

In [26]:
array2[:, 2]

array([3, 6, 3, 7])

In [28]:
# d) Pegue as linhas 1 e 2 de uma matriz 4x4.
array2[0:2]

array([[ 1,  0,  3,  5],
       [ 1,  1,  6, 11]])

## 3. Operações Matemáticas

- a) Calcule a soma de todos os elementos de `np.arange(1, 11)`;
- b) Calcue a média e o desvio padrão dos números de 1 a 20;
- c) Crie um array `[2, 4, 6, 8, 10]` e eleve todos os elementos ao quadrado;

In [2]:
# a) Calcule a soma de todos os elementos de np.arange(1, 11);
array3 = np.arange(1, 11)

array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
array3.sum()

np.int64(55)

In [8]:
# b) Calcue a média e o desvio padrão dos números de 1 a 20;
array4 = np.arange(1, 21)

np.mean(array4) # Média

np.float64(10.5)

In [9]:
np.std(array4) # Desvio Padrão

np.float64(5.766281297335398)

In [7]:
# c) Crie um array [2, 4, 6, 8, 10] e eleve todos os elementos ao quadrado;
array_c = np.array([2, 4, 6, 8, 10])

array_c ** 2

array([  4,  16,  36,  64, 100])

## 4. Funções Estatísticas

- a) Gere um array de 30 números aleatórios entre 0 e 100 e calcule:
  - média;
  - Mediana;
  - Desvio padrão; e
  - Variância.
-  b) Calcule o percentil 25, 50 e 75 do array acima;
-  c) Calcule o quantil 0.1 e 0.9 desse mesmo array.

## 5. Álgebra Linear

- a) Crie duas matrizes 2x2 e faça a multiplicação matricial entre elas;
- b) Calcule a transposta de uma matriz 3x2;
- c) Gere uma matriz 3x3 aleatória e calcule seu determinante.

In [10]:
# a) Crie duas matrizes 2x2 e faça a multiplicação matricial entre elas;
a1 = np.array([ [1, 2], [3, 4] ])
a2 = np.array([ [5, 6], [7, 8] ])

np.dot(a1, a2)

array([[19, 22],
       [43, 50]])

In [21]:
# b) Calcule a transposta de uma matriz 3x2;
b1 = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b_transposta = np.transpose(b1) # OU pode-se utilizar apenas: b.T
b_transposta

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
# c) Gere uma matriz 3x3 aleatória e calcule seu determinante.

c1 = np.arange(1, 10) # Gerara um array de 1 a 9

c1_matriz = c1.reshape(3, 3) # Fará uma recolocação do array para transformar em matriz 3x3

c1_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Calculando o determinando
np.linalg.det(c1_matriz) # O resultado é que o determinante dessa matriz é zero (pois as linhas são linearmente dependentes).

np.float64(0.0)

## 6. Manipulação de arrays

- a) Gere um array de 12 elementos e transforme-o em matriz 3x4;
- b) Transforme uma matriz 4x4 em um vetor 1D (flatten);
- c) Concatene dois arrays `[1, 2, 3]` e `[4, 5, 6]`.

In [22]:
# a) Gere um array de 12 elementos e transforme-o em matriz 3x4;

array6 = np.arange(1, 13)

matriz6 = array6.reshape(3, 4)

matriz6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# b) Transforme uma matriz 4x4 em um vetor 1D (flatten);
# Para o exemplo irei usar a matriz anterior, para facilitar

matriz6.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 7. Desafios Extras

- a) Gere 200 valores aleatórios com média 50 e desvio padrão 10, e filtre apenas os valores acima de 65;
- b) Crie uma matriz 6x6 com números aleatórios inteiros entre 10 e 100, e filtre apenas os valores menores que 30;
- c) Calcule a soma de cada coluna de uma matriz 5x3 aleatória.