# Comparações e indexação booleana

In [1]:
import numpy as np

In [2]:
# Criação dos arrays:
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print("X: \n", x)
print("Y: \n", y)

X: 
 [[1 2]
 [3 4]]
Y: 
 [1.5 3.5]


#### ========================================================

#### Comparações ponto a ponto

In [5]:
print(f"Comparação de um array com um escalar (>): \n{x > 2}")
print()
print(f"Comparação de um array com um escalar (>=): \n{x >= 2}")
print()
print(f"Comparação de um array com um escalar (<)): \n{x < 2}")
print()
print(f"Comparação de um array com um escalar (<=): \n{x <= 2}")
print()
print(f"Comparação entre arrays (==): \n{x == x}")
print()
print(f"Comparação entre arrays (>): \n{x > x}")
print()
print(f"Comparação entre arrays (>): \n{x > y}")  # broadcasting
print()

Comparação de um array com um escalar (>): 
[[False False]
 [ True  True]]

Comparação de um array com um escalar (>=): 
[[False  True]
 [ True  True]]

Comparação de um array com um escalar (<)): 
[[ True False]
 [False False]]

Comparação de um array com um escalar (<=): 
[[ True  True]
 [False False]]

Comparação entre arrays (==): 
[[ True  True]
 [ True  True]]

Comparação entre arrays (>): 
[[False False]
 [False False]]

Comparação entre arrays (>): 
[[False False]
 [ True  True]]



#### ========================================================

### Indexação Booleana

In [6]:
x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])

print("X:\n", x)

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [10]:
# indexação booleana: retornar o número de elementos maiores que 'k'
k = 10
condicao = x > k

print(f"Condição: \n {condicao}")
print(f"\nElementos maiores que {k}: {(x[condicao])}")
print(f"Número de elementos maiores que {k}: {len(x[condicao])}")

Condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]

Elementos maiores que 10: [11 21 42]
Número de elementos maiores que 10: 3


In [12]:
# indexação booleana: extração dos números pares
print("X:\n", x)

condicao = x % 2 == 0

print(f"\nCondição: \n {condicao}")
print(f"\nNúmeros pares: {x[condicao]}")

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]

Números pares: [ 4 42  8]


In [13]:
# indexação booleana: extração dos números ímpares
print("X:\n", x)

condicao = x % 2 == 1

print(f"\nCondição: \n {condicao}")
print(f"\nNúmeros ímpares: {x[condicao]}")

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]

Números ímpares: [ 1  3  7 11 21  9]
