# Indexação de arrays

In [1]:
import numpy as np

In [2]:
# os índices no Python vão de 0 a n-1,
# onde n é o tamanho da dimensão.

# Criando uma matriz 1D:
x = np.linspace(start=10, stop=100, num=10) 
print("X: ", x)
print("Shape: ", x.shape)

X:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Shape:  (10,)


**=======================================================================**
### Extração de elementos

In [5]:
print("Matriz 1D - X: ", x)
print("Primeiro elemento: ", x[0])
print("Segundo elemento: ", x[1])
print("Último elemento: ", x[9])
print("Último elemento: ", x[-1])

Matriz 1D - X:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Primeiro elemento:  10.0
Segundo elemento:  20.0
Último elemento:  100.0
Último elemento:  100.0


**=======================================================================**
### Slicing: extração de subarrays

In [6]:
print("Matriz 1D - X: ", x)
print("Dois primeiros elementos: ", x[0:2])
print("Dois primeiros elementos: ", x[:2])
print("Dois últimos elementos: ", x[-2:])

Matriz 1D - X:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Dois primeiros elementos:  [10. 20.]
Dois primeiros elementos:  [10. 20.]
Dois últimos elementos:  [ 90. 100.]


**=======================================================================**
### Slicing em arrays 2D (matrizes)

In [7]:
x = x.reshape(2, 5)  # reshape de x para 2 linhas e 5 colunas
print("X:\n", x)

X:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [8]:
# Extração de elementos:
print("Primeira linha, Segunda coluna: ", x[0, 1])
print("Segunda linha, Penúltima coluna: ", x[1, -2])
print("Última linha, Última coluna: ", x[1, 4])
print("Última linha, Última coluna: ", x[-1, -1])

Primeira linha, Segunda coluna:  20.0
Segunda linha, Penúltima coluna:  90.0
Última linha, Última coluna:  100.0
Última linha, Última coluna:  100.0


In [9]:
# slicing: extração de subarrays:
print("x:\n", x)
print("Primeira linha inteira: ", x[0, :])
print("Primeira linha, Segunda a quarta coluna: ", x[0, 1:4])
print("Última coluna inteira:\n ", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
Primeira linha inteira:  [10. 20. 30. 40. 50.]
Primeira linha, Segunda a quarta coluna:  [20. 30. 40.]
Última coluna inteira:
  [[ 50.]
 [100.]]
