# Operações úteis em Numpy

In [1]:
import numpy as np

In [3]:
# Criação do array:
x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])

print("X: \n", x)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


#### ___________________________________________________________________
***Reshape***: transformar a matriz em um vetor coluna

In [11]:
# O array criado é 3x3, então 3*3 = 9 
# então, a partir de uma matriz bidimensional, criaremos uma unidimensional.

print(f"Transformação de matriz em um vetor coluna: \n {x.reshape(9, 1)}")
# 9 linhas / 1 coluna

Transformação de matriz em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [7]:
# Transposição de matriz:
# O que é coluna, vira linha
# E o que é linha, vira coluna

print(f"X transposta: \n {x.T}")

X transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


#### Soma da matriz

In [14]:
# np.sum = soma em um dados eixo, axis{0 : linha, 1 : coluna}
print("X:\n", x)

print(f"\nSoma de todos os elementos de X: {np.sum(x)}")
print(f"Soma de X ao longo das linhas: {np.sum(x, axis=0)}")
print(f"Soma de X ao longo das colunas: {np.sum(x, axis=1)}")

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Soma de todos os elementos de X: 106
Soma de X ao longo das linhas: [47 22 37]
Soma de X ao longo das colunas: [11 36 59]


#### Média da matriz

In [15]:
# np.mean = média em um dado eixo, axis = {0 : linha, 1 : coluna}
print("X:\n", x)

print(f"\nMédia de todos os elementos de X: {np.mean(x)}")
print(f"Média de X ao longo das linhas: {np.mean(x, axis=0)}")
print(f"Média de X ao longo das colunas: {np.mean(x, axis=1)}")

# Obs: para a mediana, basta utilizar np.median

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Média de todos os elementos de X: 11.777777777777779
Média de X ao longo das linhas: [15.66666667  7.33333333 12.33333333]
Média de X ao longo das colunas: [ 3.66666667 12.         19.66666667]


#### Encontrar um índice na matriz

In [16]:
# np.where, identificação dos índices onde uma dada condição é atendida
# Uso conjunto com indexação booleana.

condicao = x % 2 == 0

print("Condição: \n", condicao)

i, j = np.where(condicao) # Indices x[i, j] = x[condicao]
print()

print("Índice i (linhas): ", i)
print("Índice j (colunas): ", j)

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]

Índice i (linhas):  [1 2 2]
Índice j (colunas):  [0 0 1]


**_________________________________________________________________________**
#### Indexação booleana e Slicing
Seleciona as linhas de **x** que possuem algum número par

In [17]:
print("X:\n", x)

condicao = x % 2 == 0
print("Condição: \n", condicao)

# Se houver alguma condição True na linha, a soma será > 0
i_row = np.where(np.sum(condicao, axis=1))[0]

print("Índice das linhas que possuem números pares: ", i_row)
print("Linhas que possuem número pares: \n", x[i_row, :])

X:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
