# Numpy

In [1]:
# importando as bibliotecas
import numpy as np

# Criação de arrays

In [2]:
# Criação de um array 1D:
lista_1d = [1, 2, 3, 4, 5]
x = np.array(lista_1d)
print(f"O array X é: {x}")
print(f"O shape é: {x.shape}")

O array X é: [1 2 3 4 5]
O shape é: (5,)


Para a criação de um array 2D, é preciso, para cada linha, se criar uma lista, então será uma lista dentro de outra lista.

Cada lista vai representar uma linha do nosso array.

In [4]:
# Criação de um array 2D:
#              linha 1       linha 2
lista_2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
y = np.array(lista_2d)
print(f"O array X é:\n {y}")
print(f"O shape é: {y.shape}")

O array X é:
 [[1 2 3 4]
 [5 6 7 8]]
O shape é: (2, 4)


**------------------------------------------------------------------------**

In [8]:
# Criar um array que contenha apenas zeros:
zerolist = (5, 2) # 5(l) são quant de linha, 2(c) são a quant de colunas.
x = np.zeros(zerolist)
print(f"O array X é:\n {x}")
print(f"O shape é: {x.shape}")

O array X é:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
O shape é: (5, 2)


In [11]:
# Criar um array que contenha apenas uns:
tamanho = (5, 5) # 1º valor é quant de linha, 2ª valor é a quant de colunas.
x = np.ones(tamanho)
print(f"O array X é:\n {x}")
print(f"O shape é: {x.shape}")

O array X é:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
O shape é: (5, 5)


**--------------------------------------------------------------**

Criação de valores dentro de um intervalo

In [12]:
# Criação de valores dentro de um intervalo com linspace

# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start = x_min, stop = x_max, num=6)
print(f"O array X é:\n {x}")
print(f"O shape é: {x.shape}")

O array X é:
 [ 5.  7.  9. 11. 13. 15.]
O shape é: (6,)


**-----------------------------------------------------------------------------------------------------------------------**


                           Matriz identidade


A matriz identidade é um tipo de matriz que sua diagonal principal é composta apenas por número 1 e seus elementos fora das diagnoais, são 0.

In [14]:
n = 4
x = np.eye(n) # eye() é para criar a matriz identidade
print(f"X:\n {x}")
print(f"\nShape: {x.shape}")

X:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Shape: (4, 4)


**-----------------------------------------------------------------------------------------------------------------------**

In [15]:
# Criação de valores aleatórios
x = np.random.random(size=(2,3))
print(f"X:\n {x}")
print(f"\nShape: {x.shape}")

X:
 [[0.10176857 0.60567453 0.02911358]
 [0.7671765  0.08657151 0.18680719]]

Shape: (2, 3)
