In [1]:
# Importando bilbioteca
import numpy as np

# Operações Aritméticas:
### Multiplicação element wise e matricial

In [2]:
# Criação de dois arrays X e Y
x = np.ones((2, 2))
y = np.eye(2)
print("X: \n", x)
print("Y: \n", y)

X: 
 [[1. 1.]
 [1. 1.]]
Y: 
 [[1. 0.]
 [0. 1.]]


In [8]:
# Multiplicação:
print("Multiplicação de dois arrays:\n ", x * y)
print("\nMultiplicação com float/int:\n ", x * 2) # briadcasting

Multiplicação de dois arrays:
  [[1. 0.]
 [0. 1.]]

Multiplicação com float/int:
  [[2. 2.]
 [2. 2.]]


In [7]:
# Multiplicação matricial:
print("Multiplicação Matricial (usando np.dot):\n ", np.dot(x, y))
print("\nMultiplicação Matricial (usando @):\n ", x @ y)
print("\nMultiplicação Matricial (usando .dot):\n ", x.dot(y))

Multiplicação Matricial (usando np.dot):
  [[1. 1.]
 [1. 1.]]

Multiplicação Matricial (usando @):
  [[1. 1.]
 [1. 1.]]

Multiplicação Matricial (usando .dot):
  [[1. 1.]
 [1. 1.]]
