In [2]:
# Importando bilbioteca
import numpy as np

# Operações Aritméticas:
### soma, subtração e divisão

In [3]:
# Criação de dois arrays X e Y
x = np.ones((2, 2))
y = np.eye(2)
print("X: \n", x)
print("Y: \n", y)

X: 
 [[1. 1.]
 [1. 1.]]
Y: 
 [[1. 0.]
 [0. 1.]]


#### Soma:

In [4]:
print("A Soma de dois arrays:\n", x + y)
print()
print("A Soma com float/int:\n", x + 2) # broadcasting

A Soma de dois arrays:
 [[2. 1.]
 [1. 2.]]

A Soma com float/int:
 [[3. 3.]
 [3. 3.]]


#### Subtração:

In [5]:
print("A Soma de dois arrays:\n", x - y)
print()
print("A Soma com float/int:\n", x - 2) # broadcasting

A Soma de dois arrays:
 [[0. 1.]
 [1. 0.]]

A Soma com float/int:
 [[-1. -1.]
 [-1. -1.]]


#### Divisão:

In [6]:
print("A Soma de dois arrays:\n", x / y)
# Vai retornar um erro (inf) porque o valor dividido por 0 vai resultar
# em algo que não existe ao certo.
print()
print("A Soma com float/int:\n", x / 2) # broadcasting

A Soma de dois arrays:
 [[ 1. inf]
 [inf  1.]]

A Soma com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


C:\Users\jvt86\AppData\Local\Temp\ipykernel_3216\3533220520.py:1: RuntimeWarning: divide by zero encountered in divide
  print("A Soma de dois arrays:\n", x / y)


#### Fazendo várias operações de uma vez:

In [7]:
print("Combinação de operações: \n", (x+y)/(x-2))

Combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]
